import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/Componets/Provider/ThemeProvider";
import Navvar from "@/Componets/Shared/Navvar";

const inter = Inter({
  weight: ["100", "200", "400", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <ThemeProvider>
          <Navvar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
